Feat senla dao 004
karabonbl4/library pull request #11
Opened 2024-03-05 15:13 UTC by karabonbl4

2024-03-09 08:48 UTC, andreitsymbalist requested changes

2024-03-09 08:48 UTC, andreitsymbalist commented on src/main/java/com/library/model/mapper/JdbcBookMapper.java
> +        if (rs.next()) {
Хорошей практикой было бы инвертировать if, чтобы не городить кучу кода в нём. Что-то вроде if(!rs.next()) throw new Excetion();

2024-03-09 08:48 UTC, andreitsymbalist commented on src/main/java/com/library/repository/postgres/impl/CriteriaBookRepositoryImpl.java
> +        if (stack == null && unit != null) {
Это явно можно упростить до вида if(param != null) predicats.add(parampredicat). Кучу ветвей не надо будет.

2024-03-09 08:48 UTC, andreitsymbalist commented on src/main/java/com/library/repository/postgres/impl/JdbcTemplateBookRepositoryImpl.java
> +        if (book.getTitle() != null) params.put("title", book.getTitle());
Понимаю нежелание переносить, но можно так не надо)) Если так лень писать, то можно сделать приватный метод в стиле putIfPresent()

2024-03-09 10:55 UTC, karabonbl4 commented on src/main/java/com/library/repository/postgres/impl/JdbcTemplateBookRepositoryImpl.java
> +        if (book.getTitle() != null) params.put("title", book.getTitle());
проверку на null перенести? если не в приватный метод, то какой еще вариант есть?

2024-03-10 16:17 UTC, andreitsymbalist approved these changes

2024-03-11 07:53 UTC, merged