Dockerfile for service, rewrote properties to yaml
karabonbl4/library pull request #9
Opened 2024-03-04 06:25 UTC by karabonbl4

2024-03-08 21:26 UTC, andreitsymbalist requested changes
Чётенько! =)
Пару правок и можно мержить

2024-03-08 21:26 UTC, andreitsymbalist commented on src/main/java/com/library/config/RabbitProperties.java
>  public class RabbitProperties {
Кажется я вспомнил, что тогда пропустил))
Давай тут замутим через @ConfigurationProperties?

2024-03-08 21:26 UTC, andreitsymbalist commented on src/main/resources/application.yaml
> +      authenticationDatabase: admin
Не критично, но в сторону clean code и code style. Формат yaml будет скорее authentication-database

2024-03-09 07:59 UTC, karabonbl4 commented on src/main/java/com/library/config/RabbitProperties.java
>  public class RabbitProperties {
не совсем понял смысл, конфиг-то все равно придется глушить(закомментить например)

2024-03-09 08:00 UTC, karabonbl4 commented on src/main/resources/application.yaml
> +      authenticationDatabase: admin
исправил

2024-03-10 16:03 UTC, andreitsymbalist approved these changes

2024-03-11 07:35 UTC, merged